source "https://rubygems.org"

gem "bundler", "2.5.21"

group :jekyll_plugins do
  gem "github-pages", "232"
  gem "jekyll-redirect-from", "0.16.0"
  gem "jekyll-include-cache", "0.2.1"
  gem "jekyll-feed", "0.17.0"
end

gem "csv", "3.3.0"
gem "webrick", "1.8.2"
gem "kramdown-parser-gfm", "1.1.0"
gem "http_parser.rb", "0.8.0"
